### ISSUE TITLE
Patch Failed NiohResolution 1.3

### ISSUE THREAD

**Issue by composingkeys** [LennardF1989/NiohResolution#18] opened 2021-09-11 19:27 UTC
Hi There,

I have Niohresolution 1.3 installed and am trying to get Nioh to run at 3440x1440 (21:9) but am running into this.

Welcome to the Nioh Resolution patcher!

Please enter your desired resolution.

-> Width [default = 1920]: 3440
-> Height [default = 1080]: 1440

Please enter a scale for your desired render resolution.

Keep in mind that this scale:

Has no effect on the entered resolution.
Has no effect on the in-game UI.
Can be less than 1.0 to increase performance.
-> Scale [default = 1.0]: 1.0

Unpacking nioh.exe...
-> Cannot process nioh.exe!

Unpacking of nioh.exe failed, this could mean the file is already unpacked and ready for patching.

Patching resolution to 3440x1440 with scale set to 1.0...
-> Patching offset 8768661
-> Patching offset 21291060
-> PATTERN_MAGIC1 expected 1, but got 0!

Patching failed, consider restoring a backup and try again.

Press any key to exit...

I didn't get the game from Steam but from Epic Games a couple of days ago. What am I doing wrong? I have Niohresoultion directly in the Nioh folder along with the original Nioh.exe file that came with the game.

**Comment by LennardF1989** [comment] 2021-09-11 19:34
Duplicate of #15 - closing.

**Closed as completed by LennardF1989** 2021-09-11 19:34 UTC
